{
 "title": "SQL Server and FlashArray - MetricsML",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "sql_instance",
    "label": "SQL Instance",
    "query": {
     "query": "query_result(sqlserver_server_properties_cpu_count{sql_instance=~\".+\"})"
    }
   },
   {
    "name": "instance",
    "label": "FlashArray",
    "query": {
     "query": "query_result(purefa_info{instance=~\".+\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(sqlserver_cpu_sqlserver_process_cpu{sql_instance=~\"^$sql_instance\"}) by (sql_instance)",
     "legendFormat": "{{sql_instance}} - Actual"
    },
    {
     "expr": "sqlserver_cpu_sqlserver_process_cpu_yhat{sql_instance=~\"^$sql_instance\"}",
     "legendFormat": "{{sql_instance}} - Predicted"
    },
    {
     "expr": "sqlserver_cpu_sqlserver_process_cpu_yhat_lower{sql_instance=~\"^$sql_instance\"}",
     "legendFormat": "{{sql_instance}} - Lower"
    },
    {
     "expr": "sqlserver_cpu_sqlserver_process_cpu_yhat_upper{sql_instance=~\"^$sql_instance\"}",
     "legendFormat": "{{sql_instance}} - Upper"
    }
   ]
  },
  {
   "title": "Wait Stats (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (sql_instance,wait_type) (irate(sqlserver_waitstats_signal_wait_time_ms{sql_instance=~\"^$sql_instance\"}[15m]))",
     "legendFormat": "{{sql_instance}} - {{wait_type}}"
    },
    {
     "expr": "avg by (sql_instance,wait_type) (irate(sqlserver_waitstats_resource_wait_time_ms{sql_instance=~\"^$sql_instance\"}[15m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Reads/Database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(sql_instance,database_name)  (rate(sqlserver_database_io_read_bytes{sql_instance=~\"$sql_instance\"}[$__rate_interval]) ) ",
     "legendFormat": "{{sql_instance}} - {{database_name}}"
    }
   ]
  },
  {
   "title": "Data Writes/Database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(sql_instance,database_name)  (rate(sqlserver_database_io_write_bytes{sql_instance=~\"$sql_instance\"}[$__rate_interval]) ) ",
     "legendFormat": "{{sql_instance}} - {{database_name}}"
    }
   ]
  }
 ]
}