{
 "title": "SQL Server and FlashArray",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "sql_instance",
    "label": "SQL Instance",
    "query": {
     "query": "query_result(sqlserver_server_properties_cpu_count{sql_instance=~\".+\"})"
    }
   },
   {
    "name": "instance",
    "label": "FlashArray",
    "query": {
     "query": "query_result(purefa_info{instance=~\".+\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(sqlserver_cpu_sqlserver_process_cpu{sql_instance=~\"^$sql_instance\"}) by (sql_instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Performance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sqlserver_performance{sql_instance=~\"$sql_instance\",counter=\"Page life expectancy\",object=\"SQLServer:Buffer Node\"}",
     "legendFormat": "{{sql_instance}} - {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Wait Stats (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (sql_instance,wait_type) (irate(sqlserver_waitstats_signal_wait_time_ms{sql_instance=~\"^$sql_instance\"}[15m]))",
     "legendFormat": "{{sql_instance}} - {{wait_type}}"
    },
    {
     "expr": "avg by (sql_instance,wait_type) (irate(sqlserver_waitstats_resource_wait_time_ms{sql_instance=~\"^$sql_instance\"}[15m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Reads/Database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(sql_instance,database_name)  (rate(sqlserver_database_io_read_bytes{sql_instance=~\"$sql_instance\"}[$__rate_interval]) ) ",
     "legendFormat": "{{sql_instance}} - {{database_name}}"
    }
   ]
  },
  {
   "title": "Data Writes/Database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(sql_instance,database_name)  (rate(sqlserver_database_io_write_bytes{sql_instance=~\"$sql_instance\"}[$__rate_interval]) ) ",
     "legendFormat": "{{sql_instance}} - {{database_name}}"
    }
   ]
  },
  {
   "title": "Volume Reads/Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(purefa_volume_performance_bandwidth_bytes{ instance=~\"^$instance\", name=~\".+$sql_instance.+\", dimension=\"read_bytes_per_sec\"}) by (instance, name) ",
     "legendFormat": "{{instance}} - {{name}}"
    }
   ]
  },
  {
   "title": "Volume Write/Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(purefa_volume_performance_bandwidth_bytes{ instance=~\"^$instance\", name=~\".+$sql_instance.+\", dimension=\"write_bytes_per_sec\"}) by (instance, name) ",
     "legendFormat": "{{instance}} - {{name}}"
    }
   ]
  },
  {
   "title": "Database Read Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(rate(sqlserver_database_io_read_latency_ms{sql_instance=~\"$sql_instance\"}[$__rate_interval]) )  / \n(rate(sqlserver_database_io_reads{sql_instance=~\"$sql_instance\"}[$__rate_interval])  ) ",
     "legendFormat": "{{sql_instance}} - {{database_name}} - {{physical_filename}} "
    }
   ]
  },
  {
   "title": "Database Write Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(irate(sqlserver_database_io_write_latency_ms{sql_instance=~\"$sql_instance\"}[$__rate_interval]) )  / \n(irate(sqlserver_database_io_writes{sql_instance=~\"$sql_instance\"}[$__rate_interval])  ) \n\n",
     "legendFormat": "{{sql_instance}} - {{database_name}}"
    }
   ]
  },
  {
   "title": "FlashArray Read Latency (μs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(purefa_volume_performance_latency_usec{instance=~\"$instance\", name=~\".+$sql_instance.+\",dimension=~\"queue_usec_per_read_op|san_usec_per_read_op|service_usec_per_read_op\"} ) by (instance,name)\n\n",
     "legendFormat": "{{instance}} - {{name}}"
    }
   ]
  },
  {
   "title": "FlashArray Write Latency (μs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(purefa_volume_performance_latency_usec{instance=~\"$instance\", name=~\".+$sql_instance.+\",dimension=~\"queue_usec_per_write_op|san_usec_per_write_op|service_usec_per_write_op\"} ) by (instance,name)",
     "legendFormat": "{{instance}} - {{name}}"
    }
   ]
  }
 ]
}